[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
region = "us-west2"
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10